# Generated by Django 4.2 on 2023-05-10 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id_contacto', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.EmailField(default=' ', max_length=50)),
                ('codigo_telefono', models.CharField(blank=True, max_length=10)),
                ('numero_telefono', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id_direccion', models.IntegerField(primary_key=True, serialize=False)),
                ('calle', models.CharField(max_length=20)),
                ('ciudad', models.CharField(max_length=20)),
                ('estado', models.CharField(max_length=20)),
                ('codigo_postal', models.CharField(max_length=4)),
                ('pais', models.CharField(max_length=25)),
                ('altura', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_empleado', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(max_length=50)),
                ('dni', models.CharField(max_length=10)),
                ('nombre_usuario', models.CharField(max_length=15)),
                ('contrasena', models.CharField(max_length=15)),
                ('tipo', models.CharField(max_length=15)),
                ('branch', models.CharField(blank=True, max_length=10, null=True)),
                ('categoria', models.CharField(blank=True, max_length=1, null=True)),
                ('id_contacto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apitecnicos.contacto')),
                ('id_direccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apitecnicos.direccion')),
            ],
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id_sucursal', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('telefono', models.CharField(max_length=15)),
                ('id_direccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apitecnicos.direccion')),
            ],
        ),
    ]
