# Generated by Django 4.2 on 2023-05-02 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_direccion', models.CharField(max_length=4)),
                ('calle', models.CharField(max_length=40)),
                ('altura', models.CharField(max_length=5)),
                ('provincia', models.CharField(max_length=40)),
                ('pais', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_sucursal', models.CharField(max_length=4)),
                ('nombre', models.CharField(max_length=20)),
                ('id_direccion', models.CharField(max_length=20)),
                ('telefono', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Taller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_taller', models.CharField(max_length=4)),
                ('nombre', models.CharField(max_length=20)),
                ('id_direccion', models.CharField(max_length=20)),
                ('id_sucursal', models.CharField(max_length=20)),
                ('mail', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Tecnico',
            fields=[
                ('id_empleado', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('dni', models.CharField(max_length=8)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('categoria', models.CharField(max_length=1)),
                ('contrasena', models.CharField(max_length=20)),
                ('id_taller', models.CharField(max_length=4)),
            ],
        ),
    ]
