# Generated by Django 4.2 on 2023-05-13 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitecnicos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='id_contacto',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id_direccion',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='Contacto',
        ),
        migrations.DeleteModel(
            name='Direccion',
        ),
    ]
