# Generated by Django 4.2 on 2023-05-03 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apitecnicos', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tecnico',
        ),
    ]
