# Generated by Django 4.2 on 2023-05-08 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitecnicos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccion',
            name='ciudad',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='codigo_postal',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='estado',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='branch',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='categoria',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
