# Generated by Django 4.2 on 2023-05-08 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitecnicos', '0002_alter_direccion_ciudad_alter_direccion_codigo_postal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='id_contacto',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='id_direccion',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
