# Generated by Django 4.2 on 2023-05-31 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitecnicos', '0002_alter_usuario_id_contacto_alter_usuario_id_direccion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('g06_id', models.IntegerField(primary_key=True, serialize=False)),
                ('g06_brand', models.CharField(max_length=20)),
                ('g06_model', models.CharField(max_length=20)),
                ('g06_year', models.CharField(max_length=4)),
                ('g06_base_price', models.FloatField(max_length=8)),
                ('g06_origin', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Paperwork',
            fields=[
                ('g07_id', models.IntegerField(primary_key=True, serialize=False)),
                ('g07_faults_debt', models.FloatField(blank=True, max_length=8, null=True)),
                ('g07_vpa', models.BooleanField(default=False)),
                ('go7_rva', models.BooleanField(default=False)),
                ('g07_vtv', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('g08_id', models.IntegerField(primary_key=True, serialize=False)),
                ('g08_model_id', models.IntegerField(max_length=8)),
                ('g08_paperwork_id', models.IntegerField(max_length=8)),
                ('g08_plate', models.CharField(max_length=10)),
                ('g08_purchase_price', models.FloatField(blank=True, max_length=8, null=True)),
                ('g08_sell_price', models.FloatField(blank=True, max_length=8, null=True)),
                ('g08_status', models.CharField(max_length=40)),
                ('g08_technical_score', models.FloatField(blank=True, max_length=8, null=True)),
                ('g08_branch', models.CharField(blank=True, max_length=10, null=True)),
                ('g08_kilometers', models.CharField(max_length=10)),
                ('g08_message', models.CharField(blank=True, null=True)),
                ('g08_combustion_type', models.CharField(blank=True)),
            ],
        ),
    ]
