# Generated by Django 4.2 on 2023-05-03 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitecnicos', '0002_delete_tecnico'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tecnico',
            fields=[
                ('id_empleado', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(max_length=50)),
                ('dni', models.CharField(max_length=10)),
                ('nombre_usuario', models.CharField(max_length=15)),
                ('contrasena', models.CharField(max_length=15)),
                ('tipo', models.CharField(max_length=15)),
                ('status', models.CharField(max_length=10)),
                ('branch', models.CharField(max_length=4)),
                ('id_contacto', models.IntegerField()),
                ('id_direccion', models.IntegerField()),
                ('categoria', models.CharField(max_length=1)),
            ],
        ),
    ]
