# Generated by Django 4.2 on 2023-05-31 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitecnicos', '0003_model_paperwork_vehicle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paperwork',
            old_name='go7_rva',
            new_name='g07_rva',
        ),
        migrations.AlterField(
            model_name='model',
            name='g06_base_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='paperwork',
            name='g07_faults_debt',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='g08_combustion_type',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='g08_model_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='g08_paperwork_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='g08_purchase_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='g08_sell_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='g08_technical_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
