# Generated by Django 4.2 on 2023-05-08 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitecnicos', '0004_alter_contacto_codigo_telefono_alter_contacto_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='codigo_telefono',
            field=models.CharField(default='+54', max_length=10),
        ),
    ]
